#!/usr/bin/env python3
from __future__ import annotations

import json
from typing import Any

from src.utils.cli_utils import sha256_text


def build_config_hash(args: Any) -> str:
    """
    Build config hash from command-line arguments for idempotency.
    
    Args:
        args: Parsed command-line arguments
        
    Returns:
        16-character hex hash of the configuration
    """
    # Best-effort: stabilize idempotency for audio-only runs.
    cfg_dump = json.dumps(
        {
            "device": args.device,
            "extractors": args.extractors,
            "asr_model_size": args.asr_model_size,
            "asr_enable_token_sequences": bool(args.asr_enable_token_sequences),
            "asr_enable_token_counts": bool(args.asr_enable_token_counts),
            "asr_enable_token_total": bool(args.asr_enable_token_total),
            "asr_enable_token_density": bool(args.asr_enable_token_density),
            "asr_enable_speech_rate": bool(args.asr_enable_speech_rate),
            "asr_enable_lang_distribution": bool(args.asr_enable_lang_distribution),
            "asr_enable_segments_with_speech": bool(args.asr_enable_segments_with_speech),
            "asr_enable_avg_segment_duration": bool(args.asr_enable_avg_segment_duration),
            "asr_enable_token_variance": bool(args.asr_enable_token_variance),
            "diarization_model_size": args.diarization_model_size,
            "diarization_batch_size": args.diarization_batch_size,
            "diarization_clustering_method": args.diarization_clustering_method,
            "diarization_speaker_count_method": args.diarization_speaker_count_method,
            "diarization_silence_peak_threshold": args.diarization_silence_peak_threshold,
            "diarization_silence_rms_threshold": args.diarization_silence_rms_threshold,
            "diar_enable_speaker_segments": bool(args.diar_enable_speaker_segments),
            "diar_enable_speaker_embeddings": bool(args.diar_enable_speaker_embeddings),
            "diar_enable_speaker_stats": bool(args.diar_enable_speaker_stats),
            "diar_enable_speaker_durations": bool(args.diar_enable_speaker_durations),
            "diar_enable_clustering_metrics": bool(args.diar_enable_clustering_metrics),
            "diar_enable_segment_embeddings": bool(args.diar_enable_segment_embeddings),
            "diar_enable_silence_detection": bool(not args.diar_disable_silence_detection),
            "emotion_model_size": args.emotion_model_size,
            "emotion_batch_size": args.emotion_batch_size,
            "emotion_silence_peak_threshold": args.emotion_silence_peak_threshold,
            "emotion_silence_rms_threshold": args.emotion_silence_rms_threshold,
            "emotion_enable_probs": bool(args.emotion_enable_probs),
            "emotion_enable_ids": bool(args.emotion_enable_ids),
            "emotion_enable_confidence": bool(args.emotion_enable_confidence),
            "emotion_enable_mean_probs": bool(args.emotion_enable_mean_probs),
            "emotion_enable_entropy": bool(args.emotion_enable_entropy),
            "emotion_enable_dominant": bool(args.emotion_enable_dominant),
            "emotion_enable_quality_metrics": bool(args.emotion_enable_quality_metrics),
            "emotion_enable_silence_detection": bool(not args.emotion_disable_silence_detection),
            "source_separation_model_size": args.source_separation_model_size,
            "source_separation_device": getattr(args, "source_separation_device", None),
            "sampling_policy_version": args.sampling_policy_version,
            "speech_analysis_pitch": bool(args.speech_analysis_pitch),
            "speech_silence_peak_threshold": float(args.speech_silence_peak_threshold),
            "speech_silence_rms_threshold": float(args.speech_silence_rms_threshold),
            "speech_enable_asr_metrics": bool(args.speech_enable_asr_metrics),
            "speech_enable_diarization_metrics": bool(args.speech_enable_diarization_metrics),
            "speech_enable_pitch_metrics": bool(args.speech_enable_pitch_metrics),
            "speech_enable_silence_detection": bool(not args.speech_disable_silence_detection),
            "quality_sample_rate": int(args.quality_sample_rate),
            "quality_frame_len_ms": float(args.quality_frame_len_ms),
            "quality_hop_ms": float(args.quality_hop_ms),
            "quality_clip_threshold": float(args.quality_clip_threshold),
            "quality_average_channels": bool(args.quality_average_channels),
            "quality_enable_normalization": bool(args.quality_enable_normalization),
            "quality_enable_basic_metrics": bool(args.quality_enable_basic_metrics),
            "quality_enable_dynamic_metrics": bool(args.quality_enable_dynamic_metrics),
            "quality_enable_frame_analysis": bool(args.quality_enable_frame_analysis),
            "quality_enable_time_series": bool(args.quality_enable_time_series),
            "mfcc_sample_rate": int(args.mfcc_sample_rate),
            "mfcc_n_mfcc": int(args.mfcc_n_mfcc),
            "mfcc_n_fft": int(args.mfcc_n_fft),
            "mfcc_hop_length": int(args.mfcc_hop_length),
            "mfcc_n_mels": int(args.mfcc_n_mels),
            "mfcc_fmin": float(args.mfcc_fmin),
            "mfcc_fmax": float(args.mfcc_fmax) if args.mfcc_fmax is not None else None,
            "mfcc_enable_audio_normalization": bool(not getattr(args, 'mfcc_disable_audio_normalization', False)),  # Default: True
            "mfcc_min_gpu_duration_sec": float(args.mfcc_min_gpu_duration_sec),
            "mfcc_min_gpu_file_size_mb": float(args.mfcc_min_gpu_file_size_mb),
            "mfcc_enable_basic_features": bool(args.mfcc_enable_basic_features),
            "mfcc_enable_deltas": bool(args.mfcc_enable_deltas),
            "mfcc_enable_time_series": bool(args.mfcc_enable_time_series),
            "mfcc_enable_normalization": bool(args.mfcc_enable_normalization),
            "mel_sample_rate": int(args.mel_sample_rate),
            "mel_n_fft": int(args.mel_n_fft),
            "mel_hop_length": int(args.mel_hop_length),
            "mel_n_mels": int(args.mel_n_mels),
            "mel_fmin": float(args.mel_fmin),
            "mel_fmax": float(args.mel_fmax) if args.mel_fmax is not None else None,
            "mel_power": float(args.mel_power),
            "mel_mix_to_mono": bool(not getattr(args, 'mel_no_mix_to_mono', False)),  # Default: True
            "mel_enable_audio_normalization": bool(not getattr(args, 'mel_disable_audio_normalization', False)),  # Default: True
            "mel_enable_basic_features": bool(args.mel_enable_basic_features),
            "mel_enable_statistics": bool(args.mel_enable_statistics),
            "mel_enable_spectral_features": bool(args.mel_enable_spectral_features),
            "mel_enable_time_series": bool(args.mel_enable_time_series),
            "mel_enable_stats_vector": bool(args.mel_enable_stats_vector),
            "onset_sample_rate": args.onset_sample_rate,
            "onset_hop_length": args.onset_hop_length,
            "onset_backend": args.onset_backend,
            "onset_enable_audio_normalization": bool(args.onset_enable_audio_normalization),
            "onset_enable_basic_features": bool(args.onset_enable_basic_features),
            "onset_enable_interval_stats": bool(args.onset_enable_interval_stats),
            "onset_enable_rhythmic_metrics": bool(args.onset_enable_rhythmic_metrics),
            "onset_enable_time_series": bool(args.onset_enable_time_series),
            "chroma_sample_rate": args.chroma_sample_rate,
            "chroma_hop_length": args.chroma_hop_length,
            "chroma_type": args.chroma_type,
            "chroma_normalize": args.chroma_normalize,
            "chroma_enable_audio_normalization": bool(args.chroma_enable_audio_normalization),
            "chroma_enable_basic_stats": bool(args.chroma_enable_basic_stats),
            "chroma_enable_extended_stats": bool(args.chroma_enable_extended_stats),
            "chroma_enable_stats_vector": bool(args.chroma_enable_stats_vector),
            "chroma_enable_time_series": bool(args.chroma_enable_time_series),
            "rhythmic_sample_rate": args.rhythmic_sample_rate,
            "rhythmic_hop_length": args.rhythmic_hop_length,
            "rhythmic_backend": args.rhythmic_backend,
            "rhythmic_start_bpm": args.rhythmic_start_bpm,
            "rhythmic_std_bpm": args.rhythmic_std_bpm,
            "rhythmic_ac_size": args.rhythmic_ac_size,
            "rhythmic_max_tempo": args.rhythmic_max_tempo,
            "rhythmic_enable_audio_normalization": bool(args.rhythmic_enable_audio_normalization),
            "rhythmic_enable_basic_metrics": bool(args.rhythmic_enable_basic_metrics),
            "rhythmic_enable_interval_stats": bool(args.rhythmic_enable_interval_stats),
            "rhythmic_enable_regularity_metrics": bool(args.rhythmic_enable_regularity_metrics),
            "rhythmic_enable_beat_times": bool(args.rhythmic_enable_beat_times),
            "rhythmic_enable_tempo_metrics": bool(args.rhythmic_enable_tempo_metrics),
            "voice_quality_sample_rate": int(args.voice_quality_sample_rate),
            "voice_quality_hnr_frame_ms": float(args.voice_quality_hnr_frame_ms),
            "voice_quality_rms_mask_threshold": float(args.voice_quality_rms_mask_threshold),
            "voice_quality_f0_fmin": float(args.voice_quality_f0_fmin),
            "voice_quality_f0_fmax": float(args.voice_quality_f0_fmax),
            "voice_quality_f0_method": args.voice_quality_f0_method,
            "voice_quality_average_channels": bool(args.voice_quality_average_channels),
            "voice_quality_enable_audio_normalization": bool(args.voice_quality_enable_audio_normalization),
            "voice_quality_enable_jitter": bool(args.voice_quality_enable_jitter),
            "voice_quality_enable_shimmer": bool(args.voice_quality_enable_shimmer),
            "voice_quality_enable_hnr": bool(args.voice_quality_enable_hnr),
            "voice_quality_enable_f0_stats": bool(args.voice_quality_enable_f0_stats),
            "voice_quality_enable_time_series": bool(args.voice_quality_enable_time_series),
            "hpss_sample_rate": int(args.hpss_sample_rate),
            "hpss_n_fft": int(args.hpss_n_fft),
            "hpss_hop_length": int(args.hpss_hop_length),
            "hpss_average_channels": bool(args.hpss_average_channels),
            "hpss_kernel_size": int(args.hpss_kernel_size),
            "hpss_margin": float(args.hpss_margin),
            "hpss_power": float(args.hpss_power),
            "hpss_enable_audio_normalization": bool(args.hpss_enable_audio_normalization),
            "hpss_enable_energy_metrics": bool(getattr(args, "hpss_enable_energy_metrics", True)) and not bool(getattr(args, "hpss_disable_energy_metrics", False)),
            "hpss_enable_waveforms": bool(args.hpss_enable_waveforms),
            "hpss_enable_spectral_features": bool(args.hpss_enable_spectral_features),
            "hpss_enable_time_series": bool(args.hpss_enable_time_series),
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return sha256_text(cfg_dump)[:16]

