core_providers:
  core_clip: true
  core_depth_midas: false
  core_optical_flow: false
  core_object_detections: false
  ocr_extractor: false
  core_face_landmarks: false
  content_domain: false
  franchise_recognition: false
  brand_semantics: false
  car_semantics: false
  face_identity: false
  place_semantics: false

modules:
  cut_detection: false
  scene_classification: false
  video_pacing: false
  uniqueness: false
  shot_quality: false
  story_structure: false
  detalize_face: false
  emotion_face: false
  behavioral: false
  optical_flow: false
  action_recognition: false
  color_light: false
  frames_composition: false
  high_level_semantic: false
  micro_emotion: false
  similarity_metrics: true
  text_scoring: false

global:
  triton_http_url: "http://localhost:8000"

core_clip:
  runtime: "inprocess"
  model_name: "ViT-B/32"
  batch_size: 16
  render:
    enable_render: true
    enable_html_render: true

similarity_metrics:
  top_n: 10
  reference_set_id: null  # optional, для тестов не используем
  ui_topk: 5
  enable_overall_score: false
  render:
    enable_render: true
    enable_html_render: true

