#!/usr/bin/env python3
from __future__ import annotations

"""
Evaluate v1 checkpoint on v1 index:
- Spearman/MAE on p50 (log1p(delta) scale) for all 6 heads
- Calibration coverage for p10/p90 if quantiles enabled
- Masked metrics for 7d
- Age-bucket breakdown

Supports golden sets (holdout/regression_mini) via fixed video_id lists.
Golden sets are generated by `Models/v1/training/generate_v1_golden_sets.py` keyed by `v1_dataset_fingerprint`.
"""

import argparse
import json
import math
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def _now_utc() -> str:
    return datetime.now(tz=timezone.utc).isoformat().replace("+00:00", "Z")


def load_index(path: str) -> "pd.DataFrame":
    import pandas as pd  # type: ignore

    p = Path(path)
    if p.suffix.lower() == ".parquet":
        return pd.read_parquet(p)
    if p.suffix.lower() == ".csv":
        return pd.read_csv(p)
    if p.suffix.lower().endswith(".jsonl"):
        return pd.read_json(p, lines=True)
    raise ValueError(f"Unsupported v1 index format: {path}")


def spearmanr(y_true: List[float], y_pred: List[float]) -> float:
    def _rankdata(x: List[float]) -> List[float]:
        pairs = [(v, i) for i, v in enumerate(x)]
        pairs.sort(key=lambda t: t[0])
        ranks = [0.0] * len(x)
        i = 0
        while i < len(pairs):
            j = i
            while j + 1 < len(pairs) and pairs[j + 1][0] == pairs[i][0]:
                j += 1
            avg = (i + 1 + j + 1) / 2.0
            for k in range(i, j + 1):
                ranks[pairs[k][1]] = avg
            i = j + 1
        return ranks

    xs = []
    ys = []
    for a, b in zip(y_true, y_pred):
        if not (math.isfinite(a) and math.isfinite(b)):
            continue
        xs.append(a)
        ys.append(b)
    if len(xs) < 2:
        return float("nan")
    rx = _rankdata(xs)
    ry = _rankdata(ys)
    mx = sum(rx) / len(rx)
    my = sum(ry) / len(ry)
    num = 0.0
    dx = 0.0
    dy = 0.0
    for a, b in zip(rx, ry):
        xa = a - mx
        yb = b - my
        num += xa * yb
        dx += xa * xa
        dy += yb * yb
    if dx <= 0.0 or dy <= 0.0:
        return float("nan")
    return num / math.sqrt(dx * dy)


def mae(y_true: List[float], y_pred: List[float]) -> float:
    s = 0.0
    n = 0
    for a, b in zip(y_true, y_pred):
        if not (math.isfinite(a) and math.isfinite(b)):
            continue
        s += abs(a - b)
        n += 1
    return float("nan") if n == 0 else s / n


def coverage(y_true: List[float], p10: List[float], p90: List[float]) -> float:
    n = 0
    c = 0
    for y, a, b in zip(y_true, p10, p90):
        if not (math.isfinite(y) and math.isfinite(a) and math.isfinite(b)):
            continue
        n += 1
        if a <= y <= b:
            c += 1
    return float("nan") if n == 0 else c / n


def age_bucket8(age_hours: float) -> str:
    if not math.isfinite(age_hours):
        return "unknown"
    if age_hours < 1.0:
        return "0-1h"
    if age_hours < 6.0:
        return "1-6h"
    if age_hours < 24.0:
        return "6-24h"
    if age_hours < 24.0 * 3:
        return "1-3d"
    if age_hours < 24.0 * 7:
        return "3-7d"
    if age_hours < 24.0 * 30:
        return "7-30d"
    if age_hours < 24.0 * 90:
        return "30-90d"
    return "90d+"


def sanity_monotonic(p10: List[float], p50: List[float], p90: List[float]) -> float:
    n = 0
    ok = 0
    for a, b, c in zip(p10, p50, p90):
        if not (math.isfinite(a) and math.isfinite(b) and math.isfinite(c)):
            continue
        n += 1
        if a <= b <= c:
            ok += 1
    return float("nan") if n == 0 else ok / n


def render_md_report(metrics: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append("# v1 evaluation report")
    lines.append("")
    lines.append(f"- created_at: `{metrics.get('created_at')}`")
    lines.append(f"- eval_set: `{metrics.get('eval_set')}`")
    lines.append(f"- checkpoint: `{metrics.get('checkpoint')}`")
    lines.append(f"- v1_index: `{metrics.get('v1_index')}`")
    lines.append(f"- encoder: `{metrics.get('encoder')}`")
    lines.append(f"- quantiles: `{metrics.get('quantiles')}`")
    lines.append(f"- rows_evaluated: `{metrics.get('rows_evaluated')}`")
    lines.append("")

    per_head = metrics.get("per_head") or {}
    for head_key in ["views_7d", "views_14d", "views_21d", "likes_7d", "likes_14d", "likes_21d"]:
        h = per_head.get(head_key)
        if not isinstance(h, dict):
            continue
        lines.append(f"## {head_key}")
        lines.append(f"- n: {h.get('n')}")
        lines.append(f"- spearman_p50: {h.get('spearman_p50')}")
        lines.append(f"- mae_p50: {h.get('mae_p50')}")
        if "coverage_p10_p90" in h:
            lines.append(f"- coverage_p10_p90: {h.get('coverage_p10_p90')}")
            lines.append(f"- sanity_p10<=p50<=p90_rate: {h.get('sanity_p10_le_p50_le_p90_rate')}")
        byb = h.get("by_age_bucket") or {}
        if byb:
            lines.append("- by_age_bucket:")
            for b, row in byb.items():
                lines.append(f"  - {b}: n={row.get('n')} spearman={row.get('spearman')} mae={row.get('mae')}")
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description="Evaluate v1 checkpoint (full quality gate)")
    p.add_argument("--v1-index", type=str, required=True)
    p.add_argument("--checkpoint", type=str, required=True)
    p.add_argument("--out-dir", type=str, required=True)
    p.add_argument("--eval-set", type=str, default="test", choices=["train", "val", "test", "holdout", "regression_mini"])
    p.add_argument("--golden-set-dir", type=str, default="", help="Directory with holdout.json/regression_mini.json")
    p.add_argument("--holdout-video-ids", type=str, default="")
    p.add_argument("--regression-video-ids", type=str, default="")
    p.add_argument("--regression-size", type=int, default=200)
    args = p.parse_args()

    import numpy as np  # type: ignore
    import torch  # type: ignore

    from Models.v1.encoder.encoder_v0 import EncoderV0, EncoderV0Config  # noqa: E402
    from Models.v1.encoder.encoder_v1 import EncoderV1, EncoderV1Config  # noqa: E402
    from Models.v1.model.v1_skeleton import V1Skeleton, V1SkeletonConfig  # noqa: E402
    from Models.v1.common.split import split_hybrid_time_channel  # noqa: E402

    df = load_index(args.v1_index)
    channel_col = "channel_id" if "channel_id" in df.columns else ("channelTitle" if "channelTitle" in df.columns else "video_id")
    df = df.assign(_split=split_hybrid_time_channel(df, channel_col=channel_col, published_col="publishedAt"))

    # select evaluation subset
    if args.eval_set in ("train", "val", "test"):
        df = df[df["_split"] == args.eval_set].copy()
        eval_set = args.eval_set
    elif args.eval_set == "holdout":
        ids_path = args.holdout_video_ids
        if args.golden_set_dir:
            ids_path = str(Path(args.golden_set_dir) / "holdout.json")
        if not ids_path:
            raise ValueError("Need --holdout-video-ids or --golden-set-dir for holdout")
        vids = set([str(v) for v in json.loads(Path(ids_path).read_text(encoding="utf-8"))])
        df = df[df["video_id"].astype(str).isin(vids)].copy()
        eval_set = "holdout"
    else:
        ids_path = args.regression_video_ids
        if args.golden_set_dir:
            ids_path = str(Path(args.golden_set_dir) / "regression_mini.json")
        if ids_path:
            vids_list = [str(v) for v in json.loads(Path(ids_path).read_text(encoding="utf-8"))]
        else:
            # deterministic sample from test split by sorted video_id
            vids_list = sorted([str(v) for v in df[df["_split"] == "test"]["video_id"].astype(str).tolist()])
            vids_list = vids_list[: min(args.regression_size, len(vids_list))]
        vids = set(vids_list)
        df = df[df["video_id"].astype(str).isin(vids)].copy()
        eval_set = "regression_mini"

    ckpt = torch.load(args.checkpoint, map_location="cpu")
    qs = tuple([float(x) for x in (ckpt.get("quantiles") or [0.5])])
    model = V1Skeleton(cfg=V1SkeletonConfig(d_model=768, quantiles=qs), d_meta=7)
    model.load_state_dict(ckpt.get("model_state_dict") or {}, strict=False)

    # encoder: if checkpoint contains trainable encoder state, use it; else deterministic v0
    encoder_kind = str(ckpt.get("encoder") or "v0")
    enc_state = ckpt.get("encoder_state_dict")
    if encoder_kind == "v1" and isinstance(enc_state, dict):
        enc = EncoderV1(cfg=EncoderV1Config(d_model=768), d_in=512)
        try:
            enc.load_state_dict(enc_state, strict=False)
        except Exception:
            pass
        enc_eval_kind = "v1"
    else:
        enc = EncoderV0(cfg=EncoderV0Config(d_model=768, seed=int(ckpt.get("seed", 1337))), d_in=512)
        enc_eval_kind = "v0"

    def load_visual_seq(row: Dict[str, Any]):
        npz_path = str(row.get("core_clip_npz_path") or "")
        seg_path = str(row.get("segmenter_metadata_path") or "")
        if not npz_path or not os.path.exists(npz_path):
            return None
        if not seg_path or not os.path.exists(seg_path):
            return None
        with np.load(npz_path, allow_pickle=True) as z:
            frame_idx = z["frame_indices"].astype("int64")
            frame_emb = z["frame_embeddings"].astype("float32")
        seg = json.loads(Path(seg_path).read_text(encoding="utf-8"))
        union_t = np.asarray(seg.get("union_timestamps_sec") or [], dtype="float32")
        if union_t.size == 0:
            return None
        times = union_t[frame_idx]
        dur = float(row.get("duration_sec") or union_t[-1])
        return frame_emb, times, dur

    meta_cols = [
        "views_0",
        "likes_0",
        "comments_0",
        "channel_subscribers_0",
        "channel_total_views_0",
        "channel_total_videos_0",
        "duration_sec",
    ]

    # quantile indices (if available)
    def _find_q(q: float) -> Optional[int]:
        for i, v in enumerate(qs):
            if abs(v - q) < 1e-6:
                return i
        return None

    iq10 = _find_q(0.1)
    iq50 = _find_q(0.5) if _find_q(0.5) is not None else 0
    iq90 = _find_q(0.9)

    # storage per head
    heads = [
        ("views", "7d", "target_views_7d", "mask_7d"),
        ("views", "14d", "target_views_14d", None),
        ("views", "21d", "target_views_21d", None),
        ("likes", "7d", "target_likes_7d", "mask_7d"),
        ("likes", "14d", "target_likes_14d", None),
        ("likes", "21d", "target_likes_21d", None),
    ]
    bucket_vals = [age_bucket8(float(v)) for v in df.get("video_age_hours_at_snapshot1", []).astype(float).fillna(float("nan")).tolist()] if "video_age_hours_at_snapshot1" in df.columns else ["unknown"] * int(df.shape[0])
    y_true: Dict[str, List[float]] = {}
    y_p50: Dict[str, List[float]] = {}
    y_p10: Dict[str, List[float]] = {}
    y_p90: Dict[str, List[float]] = {}
    buckets: Dict[str, List[str]] = {}

    for _, rr in df.iterrows():
        row = rr.to_dict()
        seq = load_visual_seq(row)
        if seq is None:
            continue
        emb, times, dur = seq
        out = enc(times_s=torch.from_numpy(times), x=torch.from_numpy(emb), duration_sec=dur)
        visual_tokens = out["summary_tokens"].unsqueeze(0)
        visual_times = out["summary_times_s"].unsqueeze(0)
        visual_mask = out["summary_mask"].unsqueeze(0)
        meta_vec = torch.tensor([[float(row.get(c, 0.0)) for c in meta_cols]], dtype=torch.float32)
        duration = torch.tensor([float(dur)], dtype=torch.float32)
        pred = model.forward(
            visual_tokens=visual_tokens,
            visual_times_s=visual_times,
            visual_mask=visual_mask,
            meta_vec=meta_vec,
            duration_sec=duration,
        )

        # per-head collection
        b = age_bucket8(float(row.get("video_age_hours_at_snapshot1", float("nan"))))
        for mod, hname, tgt_col, mask_col in heads:
            if mask_col is not None and float(row.get(mask_col, 0.0)) <= 0.0:
                continue
            tgt = float(row.get(tgt_col, float("nan")))
            if mod == "views":
                idx_h = {"7d": 0, "14d": 1, "21d": 2}[hname]
                vec = pred["views"][0, idx_h, :].detach().cpu().numpy().tolist()
            else:
                idx_h = {"7d": 0, "14d": 1, "21d": 2}[hname]
                vec = pred["likes"][0, idx_h, :].detach().cpu().numpy().tolist()
            key = f"{mod}_{hname}"
            y_true.setdefault(key, []).append(tgt)
            y_p50.setdefault(key, []).append(float(vec[iq50]))
            if iq10 is not None:
                y_p10.setdefault(key, []).append(float(vec[iq10]))
            if iq90 is not None:
                y_p90.setdefault(key, []).append(float(vec[iq90]))
            buckets.setdefault(key, []).append(b)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    per_head: Dict[str, Any] = {}
    for mod, hname, _, _ in heads:
        key = f"{mod}_{hname}"
        yt = y_true.get(key, [])
        yp50 = y_p50.get(key, [])
        by_bucket: Dict[str, Any] = {}
        # bucket metrics
        bks = buckets.get(key, [])
        for b in sorted(set(bks)):
            idxs = [i for i, bb in enumerate(bks) if bb == b]
            t_b = [yt[i] for i in idxs]
            p_b = [yp50[i] for i in idxs]
            by_bucket[b] = {"n": len(t_b), "spearman": spearmanr(t_b, p_b), "mae": mae(t_b, p_b)}

        entry: Dict[str, Any] = {
            "n": len(yt),
            "spearman_p50": spearmanr(yt, yp50),
            "mae_p50": mae(yt, yp50),
            "by_age_bucket": by_bucket,
        }
        if iq10 is not None and iq90 is not None:
            entry["coverage_p10_p90"] = coverage(yt, y_p10.get(key, []), y_p90.get(key, []))
            entry["sanity_p10_le_p50_le_p90_rate"] = sanity_monotonic(y_p10.get(key, []), yp50, y_p90.get(key, []))
        per_head[key] = entry

    metrics = {
        "created_at": _now_utc(),
        "eval_set": eval_set,
        "channel_col_used": channel_col,
        "quantiles": list(qs),
        "encoder": enc_eval_kind,
        "checkpoint": args.checkpoint,
        "v1_index": args.v1_index,
        "rows_evaluated": int(sum(len(v) for v in y_true.values()) / max(1, len(per_head))),
        "per_head": per_head,
    }
    (out_dir / "metrics.json").write_text(json.dumps(metrics, ensure_ascii=False, indent=2), encoding="utf-8")
    (out_dir / "report.md").write_text(render_md_report(metrics), encoding="utf-8")
    print(f"[ok] wrote v1 eval metrics -> {out_dir / 'metrics.json'}")
    print(f"[ok] wrote v1 eval report  -> {out_dir / 'report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


